### ISSUE TITLE
npm run prod fails

### ISSUE THREAD

**Issue by kyle-cyberprairie** [gregsullivan/_tw#117]
I can run `npm run prod` on my local machine, but on my staging server I get this error:
```
/home/forge/staging.mywebsite.com/mywebsite2024/node_modules/tailwindcss/node_modules/postcss-selector-parser/dist/selectors/attribute.js:18
var warnOfDeprecatedValueAssignment = deprecate(function () {}, "Assigning an attribute a value containing characters that might need to be escaped is deprecated. " + "Call attribute.setValue() instead.");
                                      ^

TypeError: deprecate is not a function
    at Object.<anonymous> (/home/forge/staging.mywebsite.com/mywebsite2024/node_modules/tailwindcss/node_modules/postcss-selector-parser/dist/selectors/attribute.js:18:39)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/forge/staging.mywebsite.com/mywebsite2024/node_modules/tailwindcss/node_modules/postcss-selector-parser/dist/parser.js:13:42)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)

Node.js v18.20.3
ERROR: "production:tailwind:frontend" exited with 1.
```
node and npm are the same version on my local, and they're even both ubuntu.

**Comment by gregsullivan** [comment]
Hello—Thanks for posting this!

Do you have a repository you can share?

[This older GitHub issue](https://github.com/tailwindlabs/tailwindcss/issues/2354) describes something very similar to what is happening to you. Is there any other overlap between what you're doing and the discussed problem?

**Comment by gregsullivan** [comment]
I'm going to close this. I'd be happy to reopen and to discuss this further if you're able to provide additional details about your issue. Thanks again!
